version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    restart: always
    ports:
      - 54326:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB:

  todonotes:
    build: ./todonotes
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate &&
      gunicorn todonotes.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: 'todonotes.settings.prod'

  nginx:
    build: ./nginx
    privileged: true
    ports:
      - 8000:80
    depends_on:
      - todonotes

  frontend:
    build: ./frontend
    privileged: true
    ports:
      - 80:80
    depends_on:
      - todonotes
