# Generated by Django 3.2.12 on 2022-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
